const countryToFlag: Record<string, string> = {
  ad: "🇦🇩", ae: "🇦🇪", af: "🇦🇫", ag: "🇦🇬", al: "🇦🇱", am: "🇦🇲", ao: "🇦🇴",
  ar: "🇦🇷", at: "🇦🇹", au: "🇦🇺", az: "🇦🇿", ba: "🇧🇦", bb: "🇧🇧", bd: "🇧🇩",
  be: "🇧🇪", bf: "🇧🇫", bg: "🇧🇬", bh: "🇧🇭", bi: "🇧🇮", bj: "🇧🇯", bn: "🇧🇳",
  bo: "🇧🇴", br: "🇧🇷", bs: "🇧🇸", bt: "🇧🇹", bw: "🇧🇼", by: "🇧🇾", bz: "🇧🇿",
  ca: "🇨🇦", cd: "🇨🇩", cf: "🇨🇫", cg: "🇨🇬", ch: "🇨🇭", ci: "🇨🇮", cl: "🇨🇱",
  cm: "🇨🇲", cn: "🇨🇳", co: "🇨🇴", cr: "🇨🇷", cu: "🇨🇺", cv: "🇨🇻", cy: "🇨🇾",
  cz: "🇨🇿", de: "🇩🇪", dj: "🇩🇯", dk: "🇩🇰", dm: "🇩🇲", do: "🇩🇴", dz: "🇩🇿",
  ec: "🇪🇨", ee: "🇪🇪", eg: "🇪🇬", er: "🇪🇷", es: "🇪🇸", et: "🇪🇹", fi: "🇫🇮",
  fj: "🇫🇯", fr: "🇫🇷", ga: "🇬🇦", gb: "🇬🇧", gd: "🇬🇩", ge: "🇬🇪", gh: "🇬🇭",
  gm: "🇬🇲", gn: "🇬🇳", gq: "🇬🇶", gr: "🇬🇷", gt: "🇬🇹", gw: "🇬🇼", gy: "🇬🇾",
  hn: "🇭🇳", hr: "🇭🇷", ht: "🇭🇹", hu: "🇭🇺", id: "🇮🇩", ie: "🇮🇪", il: "🇮🇱",
  in: "🇮🇳", iq: "🇮🇶", ir: "🇮🇷", is: "🇮🇸", it: "🇮🇹", jm: "🇯🇲", jo: "🇯🇴",
  jp: "🇯🇵", ke: "🇰🇪", kg: "🇰🇬", kh: "🇰🇭", ki: "🇰🇮", km: "🇰🇲", kn: "🇰🇳",
  kp: "🇰🇵", kr: "🇰🇷", kw: "🇰🇼", kz: "🇰🇿", la: "🇱🇦", lb: "🇱🇧", lc: "🇱🇨",
  li: "🇱🇮", lk: "🇱🇰", lr: "🇱🇷", ls: "🇱🇸", lt: "🇱🇹", lu: "🇱🇺", lv: "🇱🇻",
  ly: "🇱🇾", ma: "🇲🇦", mc: "🇲🇨", md: "🇲🇩", me: "🇲🇪", mg: "🇲🇬", mk: "🇲🇰",
  ml: "🇲🇱", mm: "🇲🇲", mn: "🇲🇳", mr: "🇲🇷", mt: "🇲🇹", mu: "🇲🇺", mv: "🇲🇻",
  mw: "🇲🇼", mx: "🇲🇽", my: "🇲🇾", mz: "🇲🇿", na: "🇳🇦", ne: "🇳🇪", ng: "🇳🇬",
  ni: "🇳🇮", nl: "🇳🇱", no: "🇳🇴", np: "🇳🇵", nr: "🇳🇷", nz: "🇳🇿", om: "🇴🇲",
  pa: "🇵🇦", pe: "🇵🇪", pg: "🇵🇬", ph: "🇵🇭", pk: "🇵🇰", pl: "🇵🇱", pt: "🇵🇹",
  py: "🇵🇾", qa: "🇶🇦", ro: "🇷🇴", rs: "🇷🇸", ru: "🇷🇺", rw: "🇷🇼", sa: "🇸🇦",
  sb: "🇸🇧", sc: "🇸🇨", sd: "🇸🇩", se: "🇸🇪", sg: "🇸🇬", si: "🇸🇮", sk: "🇸🇰",
  sl: "🇸🇱", sm: "🇸🇲", sn: "🇸🇳", so: "🇸🇴", sr: "🇸🇷", ss: "🇸🇸", st: "🇸🇹",
  sv: "🇸🇻", sy: "🇸🇾", sz: "🇸🇿", td: "🇹🇩", tg: "🇹🇬", th: "🇹🇭", tj: "🇹🇯",
  tl: "🇹🇱", tm: "🇹🇲", tn: "🇹🇳", to: "🇹🇴", tr: "🇹🇷", tt: "🇹🇹", tv: "🇹🇻",
  tw: "🇹🇼", tz: "🇹🇿", ua: "🇺🇦", ug: "🇺🇬", us: "🇺🇸", uy: "🇺🇾", uz: "🇺🇿",
  va: "🇻🇦", vc: "🇻🇨", ve: "🇻🇪", vn: "🇻🇳", vu: "🇻🇺", ws: "🇼🇸", ye: "🇾🇪",
  za: "🇿🇦", zm: "🇿🇲", zw: "🇿🇼",
};

const countryNames: Record<string, string> = {
  ad: "Andorra", ae: "VAE", af: "Afghanistan", ag: "Antigua", al: "Albanië", am: "Armenië",
  ao: "Angola", ar: "Argentinië", at: "Oostenrijk", au: "Australië", az: "Azerbeidzjan",
  ba: "Bosnië", bb: "Barbados", bd: "Bangladesh", be: "België", bg: "Bulgarije",
  bh: "Bahrein", bo: "Bolivia", br: "Brazilië", bs: "Bahama's", by: "Belarus",
  ca: "Canada", ch: "Zwitserland", cl: "Chili", cm: "Kameroen", cn: "China",
  co: "Colombia", cr: "Costa Rica", cu: "Cuba", cy: "Cyprus", cz: "Tsjechië",
  de: "Duitsland", dk: "Denemarken", do: "Dominicaanse Rep.", dz: "Algerije",
  ec: "Ecuador", ee: "Estland", eg: "Egypte", es: "Spanje", et: "Ethiopië",
  fi: "Finland", fr: "Frankrijk", gb: "VK", ge: "Georgië", gh: "Ghana",
  gr: "Griekenland", gt: "Guatemala", hn: "Honduras", hr: "Kroatië", hu: "Hongarije",
  id: "Indonesië", ie: "Ierland", il: "Israël", in: "India", iq: "Irak",
  ir: "Iran", is: "IJsland", it: "Italië", jm: "Jamaica", jo: "Jordanië",
  jp: "Japan", ke: "Kenia", kg: "Kirgizië", kh: "Cambodja", kr: "Zuid-Korea",
  kw: "Koeweit", kz: "Kazachstan", la: "Laos", lb: "Libanon", li: "Liechtenstein",
  lk: "Sri Lanka", lt: "Litouwen", lu: "Luxemburg", lv: "Letland", ly: "Libië",
  ma: "Marokko", md: "Moldavië", me: "Montenegro", mk: "Noord-Macedonië",
  ml: "Mali", mm: "Myanmar", mn: "Mongolië", mt: "Malta", mu: "Mauritius",
  mx: "Mexico", my: "Maleisië", mz: "Mozambique", na: "Namibië", ng: "Nigeria",
  ni: "Nicaragua", nl: "Nederland", no: "Noorwegen", np: "Nepal", nz: "Nieuw-Zeeland",
  om: "Oman", pa: "Panama", pe: "Peru", ph: "Filipijnen", pk: "Pakistan",
  pl: "Polen", pt: "Portugal", py: "Paraguay", qa: "Qatar", ro: "Roemenië",
  rs: "Servië", ru: "Rusland", rw: "Rwanda", sa: "Saoedi-Arabië", se: "Zweden",
  sg: "Singapore", si: "Slovenië", sk: "Slowakije", sn: "Senegal", so: "Somalië",
  sv: "El Salvador", sy: "Syrië", th: "Thailand", tj: "Tadzjikistan", tn: "Tunesië",
  tr: "Turkije", tt: "Trinidad", tw: "Taiwan", tz: "Tanzania", ua: "Oekraïne",
  ug: "Oeganda", us: "VS", uy: "Uruguay", uz: "Oezbekistan", ve: "Venezuela",
  vn: "Vietnam", za: "Zuid-Afrika", zm: "Zambia", zw: "Zimbabwe",
};

export const getCountryFlag = (code: string): string => countryToFlag[code.toLowerCase()] ?? "🌍";
export const getCountryName = (code: string): string => countryNames[code.toLowerCase()] ?? code.toUpperCase();
